/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstallRouteImport } from './routes/install'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PayInvoiceIdRouteImport } from './routes/pay.$invoiceId'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSendRouteImport } from './routes/app.send'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppMorphRouteImport } from './routes/app.morph'
import { Route as AppLedgerRouteImport } from './routes/app.ledger'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppDocsRouteImport } from './routes/app.docs'
import { Route as AppBatchRouteImport } from './routes/app.batch'
import { Route as AppAssistRouteImport } from './routes/app.assist'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as ApiWatchedWalletsRouteImport } from './routes/api.watched-wallets'
import { Route as ApiVaultRecordsRouteImport } from './routes/api.vault-records'
import { Route as ApiRecordsRouteImport } from './routes/api.records'
import { Route as ApiPublicInvoiceRouteImport } from './routes/api.public-invoice'
import { Route as ApiInvoicesRouteImport } from './routes/api.invoices'
import { Route as ApiInvoicePaymentRouteImport } from './routes/api.invoice-payment'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiExtensionPairRouteImport } from './routes/api.extension-pair'
import { Route as ApiExtensionIntentRouteImport } from './routes/api.extension-intent'
import { Route as ApiDatabaseResetRouteImport } from './routes/api.database-reset'
import { Route as ApiBatchPayoutsRouteImport } from './routes/api.batch-payouts'
import { Route as ApiAgentPaymentIntentRouteImport } from './routes/api.agent-payment-intent'
import { Route as ApiAgentMemoryRouteImport } from './routes/api.agent-memory'
import { Route as ApiCronScanMorphRouteImport } from './routes/api.cron.scan-morph'

const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PayInvoiceIdRoute = PayInvoiceIdRouteImport.update({
  id: '/pay/$invoiceId',
  path: '/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMorphRoute = AppMorphRouteImport.update({
  id: '/morph',
  path: '/morph',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchRoute = AppBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistRoute = AppAssistRouteImport.update({
  id: '/assist',
  path: '/assist',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const ApiWatchedWalletsRoute = ApiWatchedWalletsRouteImport.update({
  id: '/api/watched-wallets',
  path: '/api/watched-wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultRecordsRoute = ApiVaultRecordsRouteImport.update({
  id: '/api/vault-records',
  path: '/api/vault-records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsRoute = ApiRecordsRouteImport.update({
  id: '/api/records',
  path: '/api/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInvoiceRoute = ApiPublicInvoiceRouteImport.update({
  id: '/api/public-invoice',
  path: '/api/public-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicePaymentRoute = ApiInvoicePaymentRouteImport.update({
  id: '/api/invoice-payment',
  path: '/api/invoice-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionPairRoute = ApiExtensionPairRouteImport.update({
  id: '/api/extension-pair',
  path: '/api/extension-pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionIntentRoute = ApiExtensionIntentRouteImport.update({
  id: '/api/extension-intent',
  path: '/api/extension-intent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatabaseResetRoute = ApiDatabaseResetRouteImport.update({
  id: '/api/database-reset',
  path: '/api/database-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBatchPayoutsRoute = ApiBatchPayoutsRouteImport.update({
  id: '/api/batch-payouts',
  path: '/api/batch-payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPaymentIntentRoute = ApiAgentPaymentIntentRouteImport.update({
  id: '/api/agent-payment-intent',
  path: '/api/agent-payment-intent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMemoryRoute = ApiAgentMemoryRouteImport.update({
  id: '/api/agent-memory',
  path: '/api/agent-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronScanMorphRoute = ApiCronScanMorphRouteImport.update({
  id: '/api/cron/scan-morph',
  path: '/api/cron/scan-morph',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/install': typeof InstallRoute
  '/api/agent-memory': typeof ApiAgentMemoryRoute
  '/api/agent-payment-intent': typeof ApiAgentPaymentIntentRoute
  '/api/batch-payouts': typeof ApiBatchPayoutsRoute
  '/api/database-reset': typeof ApiDatabaseResetRoute
  '/api/extension-intent': typeof ApiExtensionIntentRoute
  '/api/extension-pair': typeof ApiExtensionPairRoute
  '/api/health': typeof ApiHealthRoute
  '/api/invoice-payment': typeof ApiInvoicePaymentRoute
  '/api/invoices': typeof ApiInvoicesRoute
  '/api/public-invoice': typeof ApiPublicInvoiceRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/vault-records': typeof ApiVaultRecordsRoute
  '/api/watched-wallets': typeof ApiWatchedWalletsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/assist': typeof AppAssistRoute
  '/app/batch': typeof AppBatchRoute
  '/app/docs': typeof AppDocsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/morph': typeof AppMorphRoute
  '/app/reports': typeof AppReportsRoute
  '/app/review': typeof AppReviewRoute
  '/app/send': typeof AppSendRoute
  '/app/settings': typeof AppSettingsRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/app/': typeof AppIndexRoute
  '/api/cron/scan-morph': typeof ApiCronScanMorphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/api/agent-memory': typeof ApiAgentMemoryRoute
  '/api/agent-payment-intent': typeof ApiAgentPaymentIntentRoute
  '/api/batch-payouts': typeof ApiBatchPayoutsRoute
  '/api/database-reset': typeof ApiDatabaseResetRoute
  '/api/extension-intent': typeof ApiExtensionIntentRoute
  '/api/extension-pair': typeof ApiExtensionPairRoute
  '/api/health': typeof ApiHealthRoute
  '/api/invoice-payment': typeof ApiInvoicePaymentRoute
  '/api/invoices': typeof ApiInvoicesRoute
  '/api/public-invoice': typeof ApiPublicInvoiceRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/vault-records': typeof ApiVaultRecordsRoute
  '/api/watched-wallets': typeof ApiWatchedWalletsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/assist': typeof AppAssistRoute
  '/app/batch': typeof AppBatchRoute
  '/app/docs': typeof AppDocsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/morph': typeof AppMorphRoute
  '/app/reports': typeof AppReportsRoute
  '/app/review': typeof AppReviewRoute
  '/app/send': typeof AppSendRoute
  '/app/settings': typeof AppSettingsRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/app': typeof AppIndexRoute
  '/api/cron/scan-morph': typeof ApiCronScanMorphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/install': typeof InstallRoute
  '/api/agent-memory': typeof ApiAgentMemoryRoute
  '/api/agent-payment-intent': typeof ApiAgentPaymentIntentRoute
  '/api/batch-payouts': typeof ApiBatchPayoutsRoute
  '/api/database-reset': typeof ApiDatabaseResetRoute
  '/api/extension-intent': typeof ApiExtensionIntentRoute
  '/api/extension-pair': typeof ApiExtensionPairRoute
  '/api/health': typeof ApiHealthRoute
  '/api/invoice-payment': typeof ApiInvoicePaymentRoute
  '/api/invoices': typeof ApiInvoicesRoute
  '/api/public-invoice': typeof ApiPublicInvoiceRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/vault-records': typeof ApiVaultRecordsRoute
  '/api/watched-wallets': typeof ApiWatchedWalletsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/assist': typeof AppAssistRoute
  '/app/batch': typeof AppBatchRoute
  '/app/docs': typeof AppDocsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/morph': typeof AppMorphRoute
  '/app/reports': typeof AppReportsRoute
  '/app/review': typeof AppReviewRoute
  '/app/send': typeof AppSendRoute
  '/app/settings': typeof AppSettingsRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/app/': typeof AppIndexRoute
  '/api/cron/scan-morph': typeof ApiCronScanMorphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/install'
    | '/api/agent-memory'
    | '/api/agent-payment-intent'
    | '/api/batch-payouts'
    | '/api/database-reset'
    | '/api/extension-intent'
    | '/api/extension-pair'
    | '/api/health'
    | '/api/invoice-payment'
    | '/api/invoices'
    | '/api/public-invoice'
    | '/api/records'
    | '/api/vault-records'
    | '/api/watched-wallets'
    | '/app/agents'
    | '/app/assist'
    | '/app/batch'
    | '/app/docs'
    | '/app/invoices'
    | '/app/ledger'
    | '/app/morph'
    | '/app/reports'
    | '/app/review'
    | '/app/send'
    | '/app/settings'
    | '/pay/$invoiceId'
    | '/app/'
    | '/api/cron/scan-morph'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/install'
    | '/api/agent-memory'
    | '/api/agent-payment-intent'
    | '/api/batch-payouts'
    | '/api/database-reset'
    | '/api/extension-intent'
    | '/api/extension-pair'
    | '/api/health'
    | '/api/invoice-payment'
    | '/api/invoices'
    | '/api/public-invoice'
    | '/api/records'
    | '/api/vault-records'
    | '/api/watched-wallets'
    | '/app/agents'
    | '/app/assist'
    | '/app/batch'
    | '/app/docs'
    | '/app/invoices'
    | '/app/ledger'
    | '/app/morph'
    | '/app/reports'
    | '/app/review'
    | '/app/send'
    | '/app/settings'
    | '/pay/$invoiceId'
    | '/app'
    | '/api/cron/scan-morph'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/install'
    | '/api/agent-memory'
    | '/api/agent-payment-intent'
    | '/api/batch-payouts'
    | '/api/database-reset'
    | '/api/extension-intent'
    | '/api/extension-pair'
    | '/api/health'
    | '/api/invoice-payment'
    | '/api/invoices'
    | '/api/public-invoice'
    | '/api/records'
    | '/api/vault-records'
    | '/api/watched-wallets'
    | '/app/agents'
    | '/app/assist'
    | '/app/batch'
    | '/app/docs'
    | '/app/invoices'
    | '/app/ledger'
    | '/app/morph'
    | '/app/reports'
    | '/app/review'
    | '/app/send'
    | '/app/settings'
    | '/pay/$invoiceId'
    | '/app/'
    | '/api/cron/scan-morph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InstallRoute: typeof InstallRoute
  ApiAgentMemoryRoute: typeof ApiAgentMemoryRoute
  ApiAgentPaymentIntentRoute: typeof ApiAgentPaymentIntentRoute
  ApiBatchPayoutsRoute: typeof ApiBatchPayoutsRoute
  ApiDatabaseResetRoute: typeof ApiDatabaseResetRoute
  ApiExtensionIntentRoute: typeof ApiExtensionIntentRoute
  ApiExtensionPairRoute: typeof ApiExtensionPairRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInvoicePaymentRoute: typeof ApiInvoicePaymentRoute
  ApiInvoicesRoute: typeof ApiInvoicesRoute
  ApiPublicInvoiceRoute: typeof ApiPublicInvoiceRoute
  ApiRecordsRoute: typeof ApiRecordsRoute
  ApiVaultRecordsRoute: typeof ApiVaultRecordsRoute
  ApiWatchedWalletsRoute: typeof ApiWatchedWalletsRoute
  PayInvoiceIdRoute: typeof PayInvoiceIdRoute
  ApiCronScanMorphRoute: typeof ApiCronScanMorphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/pay/$invoiceId': {
      id: '/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof PayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/send': {
      id: '/app/send'
      path: '/send'
      fullPath: '/app/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/morph': {
      id: '/app/morph'
      path: '/morph'
      fullPath: '/app/morph'
      preLoaderRoute: typeof AppMorphRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batch': {
      id: '/app/batch'
      path: '/batch'
      fullPath: '/app/batch'
      preLoaderRoute: typeof AppBatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assist': {
      id: '/app/assist'
      path: '/assist'
      fullPath: '/app/assist'
      preLoaderRoute: typeof AppAssistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/watched-wallets': {
      id: '/api/watched-wallets'
      path: '/api/watched-wallets'
      fullPath: '/api/watched-wallets'
      preLoaderRoute: typeof ApiWatchedWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault-records': {
      id: '/api/vault-records'
      path: '/api/vault-records'
      fullPath: '/api/vault-records'
      preLoaderRoute: typeof ApiVaultRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records': {
      id: '/api/records'
      path: '/api/records'
      fullPath: '/api/records'
      preLoaderRoute: typeof ApiRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-invoice': {
      id: '/api/public-invoice'
      path: '/api/public-invoice'
      fullPath: '/api/public-invoice'
      preLoaderRoute: typeof ApiPublicInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice-payment': {
      id: '/api/invoice-payment'
      path: '/api/invoice-payment'
      fullPath: '/api/invoice-payment'
      preLoaderRoute: typeof ApiInvoicePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension-pair': {
      id: '/api/extension-pair'
      path: '/api/extension-pair'
      fullPath: '/api/extension-pair'
      preLoaderRoute: typeof ApiExtensionPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension-intent': {
      id: '/api/extension-intent'
      path: '/api/extension-intent'
      fullPath: '/api/extension-intent'
      preLoaderRoute: typeof ApiExtensionIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/database-reset': {
      id: '/api/database-reset'
      path: '/api/database-reset'
      fullPath: '/api/database-reset'
      preLoaderRoute: typeof ApiDatabaseResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/batch-payouts': {
      id: '/api/batch-payouts'
      path: '/api/batch-payouts'
      fullPath: '/api/batch-payouts'
      preLoaderRoute: typeof ApiBatchPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-payment-intent': {
      id: '/api/agent-payment-intent'
      path: '/api/agent-payment-intent'
      fullPath: '/api/agent-payment-intent'
      preLoaderRoute: typeof ApiAgentPaymentIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-memory': {
      id: '/api/agent-memory'
      path: '/api/agent-memory'
      fullPath: '/api/agent-memory'
      preLoaderRoute: typeof ApiAgentMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/scan-morph': {
      id: '/api/cron/scan-morph'
      path: '/api/cron/scan-morph'
      fullPath: '/api/cron/scan-morph'
      preLoaderRoute: typeof ApiCronScanMorphRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppAssistRoute: typeof AppAssistRoute
  AppBatchRoute: typeof AppBatchRoute
  AppDocsRoute: typeof AppDocsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppMorphRoute: typeof AppMorphRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSendRoute: typeof AppSendRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppAssistRoute: AppAssistRoute,
  AppBatchRoute: AppBatchRoute,
  AppDocsRoute: AppDocsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppMorphRoute: AppMorphRoute,
  AppReportsRoute: AppReportsRoute,
  AppReviewRoute: AppReviewRoute,
  AppSendRoute: AppSendRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InstallRoute: InstallRoute,
  ApiAgentMemoryRoute: ApiAgentMemoryRoute,
  ApiAgentPaymentIntentRoute: ApiAgentPaymentIntentRoute,
  ApiBatchPayoutsRoute: ApiBatchPayoutsRoute,
  ApiDatabaseResetRoute: ApiDatabaseResetRoute,
  ApiExtensionIntentRoute: ApiExtensionIntentRoute,
  ApiExtensionPairRoute: ApiExtensionPairRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInvoicePaymentRoute: ApiInvoicePaymentRoute,
  ApiInvoicesRoute: ApiInvoicesRoute,
  ApiPublicInvoiceRoute: ApiPublicInvoiceRoute,
  ApiRecordsRoute: ApiRecordsRoute,
  ApiVaultRecordsRoute: ApiVaultRecordsRoute,
  ApiWatchedWalletsRoute: ApiWatchedWalletsRoute,
  PayInvoiceIdRoute: PayInvoiceIdRoute,
  ApiCronScanMorphRoute: ApiCronScanMorphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
